# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_url', models.CharField(max_length=2048)),
                ('g_from', models.IntegerField()),
                ('g_name', models.CharField(max_length=256)),
                ('price_lasted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_moniter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('needs_update', models.BooleanField()),
                ('stock', models.IntegerField()),
                ('status', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('category', models.CharField(max_length=256, verbose_name='\u5206\u7c7b')),
            ],
        ),
    ]
