# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(max_length=256, null=True, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_from',
            field=models.IntegerField(choices=[(1, '\u6dd8\u5b9d'), (2, '\u5176\u4ed6\uff08\u6682\u672a\u652f\u6301\uff09')], default=1, verbose_name='\u5546\u54c1\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_name',
            field=models.CharField(max_length=256, null=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_url',
            field=models.CharField(max_length=2048, verbose_name='\u5546\u54c1\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='needs_update',
            field=models.BooleanField(verbose_name='\u662f\u5426\u9700\u8981\u66f4\u65b0'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_lasted',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='\u6700\u65b0\u5b98\u7f51\u4ef7'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_moniter',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='\u76d1\u63a7\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(choices=[(-1, '\u505c\u6b62\u66f4\u65b0'), (1, '\u6b63\u5e38\u66f4\u65b0')], default=1, verbose_name='\u76d1\u63a7\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='\u5e93\u5b58'),
        ),
    ]
